make base image of scratch image workflow configurable

diff --git a/.github/workflows/scratch-image.yaml b/.github/workflows/scratch-image.yaml
--- a/.github/workflows/scratch-image.yaml
+++ b/.github/workflows/scratch-image.yaml
@@ -31,10 +31,12 @@
 
 name: Distroless Docker Image
 on:
-  push:
-    branches:
-    - lars/scratch-build
   workflow_dispatch:
+    inputs:
+      baseImage:
+        description: 'The base image for the resulting docker image. Must be either "alpine" or "scratch"'
+        required: true
+        default: 'alpine'
 jobs:
   build-image:
     name: Build and publish docker image
@@ -42,6 +44,21 @@ jobs:
     strategy:
       fail-fast: false
     steps:
+    - name: validate inputs
+      run: |
+        case "${{ github.event.inputs.baseImage }}" in
+          alpine)
+            echo "::debug::Using 'alpine' base base image"
+            ;;
+          scratch)
+            echo "::debug::Using 'scratch' base base image"
+            ;;
+          *)
+            echo "::error::Unsupport base image input. Valid values are 'alpine' or 'scratch'"
+            exit 1
+            ;;
+        esac
+
     - name: Check out the repo
       uses: actions/checkout@v2
 
@@ -90,7 +107,7 @@ jobs:
         RUN strip -s chainweb-node
         RUN cabal freeze
 
-        FROM scratch
+        FROM ${{ github.event.inputs.baseImage }}
         COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs/
         COPY --from=builder /chainweb-node/chainweb-node /usr/bin/chainweb-node
         COPY --from=builder /chainweb-node/LICENSE /usr/local/share/chainweb/
@@ -106,7 +123,7 @@ jobs:
       id: docker_meta
       uses: crazy-max/ghaction-docker-meta@v1
       with:
-        images: ghcr.io/kadena-io/chainweb-node-scratch
+        images: ghcr.io/kadena-io/chainweb-node-${{ github.event.inputs.baseImage }}
         tag-sha: true
 
     - name: Set up QEMU
